export default [
    { url: 'https://saiosore.github.io/portfolio/test/assets/c1.png', width: 283, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/c2.png', width: 283, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/c3.png', width: 300, height: 298 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/c4.png', width: 300, height: 228 },
    // { url: 'https://saiosore.github.io/portfolio/test/assets/c5.png', width: 261, height: 300 },
    // { url: 'https://saiosore.github.io/portfolio/test/assets/c6.png', width: 300, height: 300 },
    // { url: 'https://saiosore.github.io/portfolio/test/assets/c7.png', width: 300, height: 272 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/c8.png', width: 289, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/c9.png', width: 296, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/c10.png', width: 300, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/c11.png', width: 300, height: 272 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/c12.png', width: 289, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/c13.png', width: 296, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/c14.png', width: 300, height: 298 },
    // { url: 'assets/img/contact/snake.png', width: 229, height: 300 },
    // { url: 'assets/img/contact/web.png', width: 298, height: 300 },
    // { url: 'assets/img/contact/elephant.png', width: 300, height: 228 },
    // { url: 'assets/img/contact/key.png', width: 300, height: 114 },
    // { url: 'assets/img/contact/diamond.png', width: 300, height: 250 },
    // { url: 'assets/img/contact/envelope.png', width: 283, height: 300 },
    // { url: 'assets/img/contact/cherub.png', width: 300, height: 268 },
]
