export default [
    { url: 'https://saiosore.github.io/portfolio/test/assets/sun.png', width: 283, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/diamond.png', width: 283, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/diamond.png', width: 300, height: 298 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/sun.png', width: 300, height: 228 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/sun.png', width: 261, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/sun.png', width: 300, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/sun.png', width: 300, height: 272 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/sun.png', width: 289, height: 300 },
    { url: 'https://saiosore.github.io/portfolio/test/assets/sun.png', width: 296, height: 300 },
    // { url: 'assets/img/contact/snake.png', width: 229, height: 300 },
    // { url: 'assets/img/contact/web.png', width: 298, height: 300 },
    // { url: 'assets/img/contact/elephant.png', width: 300, height: 228 },
    // { url: 'assets/img/contact/key.png', width: 300, height: 114 },
    // { url: 'assets/img/contact/diamond.png', width: 300, height: 250 },
    // { url: 'assets/img/contact/envelope.png', width: 283, height: 300 },
    // { url: 'assets/img/contact/cherub.png', width: 300, height: 268 },
]
